#!/usr/bin/env python3
"""Regenerate database/schema.sql from a live apt_intel.db so the published schema
tracks reality instead of drifting.

Run this after any schema migration (and it is safe to run anytime):

    python3 scripts/regen_schema.py [/path/to/apt_intel.db]
        # default DB: /opt/apt-intel/database/apt_intel.db

Excluded from the published schema:
  * sqlite_* internal objects (sqlite_sequence, sqlite_stat1, autoindexes)
  * api_keys / api_queries  -- server-internal auth + audit-log tables; their structure
    is not published (no benefit to contributors, minor recon hint otherwise).
Everything else (tables, views, indexes, triggers) is emitted in dependency-safe order.
Read-only on the DB.
"""
import os
import sqlite3
import sys

DEFAULT_DB = "/opt/apt-intel/database/apt_intel.db"
EXCLUDE = {"api_keys", "api_queries"}  # server-internal auth/audit -- not published

HEADER = [
    "-- APT Watch -- database schema (PUBLISHED copy).",
    "-- AUTO-GENERATED by scripts/regen_schema.py from the live DB. Do NOT hand-edit;",
    "-- re-run the script after a schema migration so this file cannot silently drift.",
    "-- Excluded: sqlite_* internals; api_keys / api_queries (server-internal auth/audit).",
    "",
]


def main(argv=None):
    argv = argv if argv is not None else sys.argv[1:]
    db_path = argv[0] if argv else DEFAULT_DB
    out_path = os.path.normpath(
        os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "database", "schema.sql")
    )
    if not os.path.exists(db_path):
        print(f"ERROR: DB not found: {db_path}", file=sys.stderr)
        return 2
    con = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    rows = con.execute(
        """
        SELECT type, name, tbl_name, sql FROM sqlite_master
        WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%'
        ORDER BY CASE type WHEN 'table' THEN 1 WHEN 'view' THEN 2
                           WHEN 'index' THEN 3 WHEN 'trigger' THEN 4 ELSE 5 END,
                 name
        """
    ).fetchall()
    con.close()

    body, kept = [], 0
    for _type, name, tbl_name, sql in rows:
        if name in EXCLUDE or tbl_name in EXCLUDE:
            continue
        body.append(sql.strip() + ";")
        kept += 1

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(HEADER + body) + "\n")
    print(f"wrote {out_path}: {kept} objects (excluded {sorted(EXCLUDE)} + sqlite_* internals)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
