#!/usr/bin/env python3
"""Regenerate a schema.sql from a live apt_intel.db so the reference schema tracks
reality instead of drifting.

Run after any schema migration (safe to run anytime, read-only on the DB):

    python3 scripts/regen_schema.py                       # public copy (auth tables redacted)
    python3 scripts/regen_schema.py --include-auth \
        --out ../APT_Analytics/apt-intel/database/schema.sql   # internal/private full copy

Defaults: --db /opt/apt-intel/database/apt_intel.db, --out ../database/schema.sql.

Always excluded: sqlite_* internals (sqlite_sequence, sqlite_stat1, autoindexes).
Excluded UNLESS --include-auth: api_keys / api_queries (server-internal auth + audit-log
tables). The PUBLISHED copy omits them (no benefit to contributors, minor recon hint);
the PRIVATE mirror can keep them with --include-auth.
Emits tables, views, indexes, triggers in dependency-safe order.
"""
import argparse
import os
import sqlite3
import sys

DEFAULT_DB = "/opt/apt-intel/database/apt_intel.db"
AUTH_TABLES = {"api_keys", "api_queries"}


def header(include_auth: bool) -> list:
    excl = "sqlite_* internals" if include_auth else "sqlite_* internals; api_keys / api_queries (auth/audit)"
    return [
        "-- APT Watch -- database schema reference.",
        "-- AUTO-GENERATED by scripts/regen_schema.py from the live DB. Do NOT hand-edit;",
        "-- re-run the script after a schema migration so this file cannot silently drift.",
        f"-- Excluded: {excl}.",
        "",
    ]


def main(argv=None):
    ap = argparse.ArgumentParser(description="Regenerate schema.sql from a live apt_intel.db")
    ap.add_argument("db", nargs="?", default=DEFAULT_DB, help=f"path to apt_intel.db (default {DEFAULT_DB})")
    ap.add_argument("--db", dest="db_opt", help="path to apt_intel.db (overrides positional)")
    ap.add_argument("--out", help="output schema.sql (default: ../database/schema.sql next to this script)")
    ap.add_argument("--include-auth", action="store_true",
                    help="keep api_keys/api_queries (use for the PRIVATE mirror only)")
    a = ap.parse_args(argv)

    db_path = a.db_opt or a.db
    out_path = a.out or os.path.normpath(
        os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "database", "schema.sql")
    )
    if not os.path.exists(db_path):
        print(f"ERROR: DB not found: {db_path}", file=sys.stderr)
        return 2

    exclude = set() if a.include_auth else set(AUTH_TABLES)
    con = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    rows = con.execute(
        """
        SELECT type, name, tbl_name, sql FROM sqlite_master
        WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%'
        ORDER BY CASE type WHEN 'table' THEN 1 WHEN 'view' THEN 2
                           WHEN 'index' THEN 3 WHEN 'trigger' THEN 4 ELSE 5 END,
                 name
        """
    ).fetchall()
    con.close()

    body, kept = [], 0
    for _type, name, tbl_name, sql in rows:
        if name in exclude or tbl_name in exclude:
            continue
        body.append(sql.strip() + ";")
        kept += 1

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(header(a.include_auth) + body) + "\n")
    note = "incl. auth" if a.include_auth else f"excl. {sorted(AUTH_TABLES)}"
    print(f"wrote {out_path}: {kept} objects ({note} + sqlite_* internals)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
